CREATE TABLE ADLOC 
(
    ADLOC_CD CHARACTER VARYING(14) NOT NULL,
    ADPOR_CD CHARACTER VARYING(10) NOT NULL,
    BLOC CHARACTER VARYING(4) NULL,
    ESCALA CHARACTER VARYING(2) NULL,
    PLANTA CHARACTER VARYING(3) NULL,
    PORTA CHARACTER VARYING(4) NULL,
    ADLOC_TX CHARACTER VARYING(50) NULL
);


CREATE TABLE ADPOR 
(
    ADPOR_CD CHARACTER VARYING(10) NOT NULL,
    PROV_CD CHARACTER VARYING(2) NOT NULL,
    MUN_CD CHARACTER VARYING(3) NOT NULL,
    CARRE_CD CHARACTER VARYING(4) NOT NULL,
    TRCAR_CD CHARACTER VARYING(6) NOT NULL,
    ADPOR_TP CHARACTER VARYING(1) NULL,
    NUMERO_1 INTEGER NULL,
    LLETRA_1 CHARACTER VARYING(1) NULL,
    NUMERO_2 INTEGER NULL,
    LLETRA_2 CHARACTER VARYING(1) NULL,
    ADPOR_KM DOUBLE PRECISION NULL,
    ADPOR_TX CHARACTER VARYING(50) NULL,
    POSTAL_CD CHARACTER VARYING(5) NULL,
    PARATGE_CD CHARACTER VARYING(5) NULL,
    PARATGE_NM CHARACTER VARYING(50) NULL,
    DOM_FINCA CHARACTER VARYING(1) NULL,
    DOM_UCONS CHARACTER VARYING(1) NULL,
    REFCAD_PAR CHARACTER VARYING(14) NULL
);


CREATE TABLE BARRI 
(
    BARRI_CD CHARACTER VARYING(3) NOT NULL,
    BARRI_NM CHARACTER VARYING(50) NULL
);


CREATE TABLE CARRE 
(
    PROV_CD CHARACTER VARYING(2) NOT NULL,
    MUN_CD CHARACTER VARYING(3) NOT NULL,
    CARRE_CD CHARACTER VARYING(4) NOT NULL,
    CARRE_DGC CHARACTER VARYING(4) NULL,
    CARRE_TP CHARACTER VARYING(5) NULL,
    CARRE_NM CHARACTER VARYING(50) NULL
);


CREATE TABLE CLSOL 
(
    CLSOL_CD CHARACTER VARYING(4) NOT NULL,
    CLSOL_DS CHARACTER VARYING(30) NULL
);


CREATE TABLE DISTR 
(
    DISTR_CD CHARACTER VARYING(2) NOT NULL,
    DISTR_LT CHARACTER VARYING(4) NULL,
    DISTR_NM CHARACTER VARYING(50) NULL
);


CREATE TABLE ECOMU 
(
    ECOMU_CD CHARACTER VARYING(10) NOT NULL,
    ECONS_CD CHARACTER VARYING(14) NOT NULL,
    MODREP CHARACTER VARYING(3) NULL
);


CREATE TABLE ECONS 
(
    ECONS_CD CHARACTER VARYING(14) NOT NULL,
    UCONS_CD CHARACTER VARYING(10) NOT NULL,
    F_DESTINO CHARACTER VARYING(3) NULL,
    F_TIPOREFORMA CHARACTER VARYING(1) NULL,
    F_ANYOREFORMA INTEGER NULL,
    F_ANTIG INTEGER NULL,
    F_LOCALINT CHARACTER VARYING(1) NULL,
    F_SUPTOTAL INTEGER NULL,
    F_SUPEXT INTEGER NULL,
    F_SUPOTRAS INTEGER NULL,
    E_TIPOLOGIA CHARACTER VARYING(5) NULL,
    E_USO CHARACTER VARYING(1) NULL,
    E_CATEGORIA CHARACTER VARYING(1) NULL,
    E_TIPOVALOR CHARACTER VARYING(1) NULL,
    E_CCCVSYC_COEF_1 DOUBLE PRECISION NULL,
    E_CCVSYC_IND_1 CHARACTER VARYING(1) NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL,
    VAL_REPER_SUELO DOUBLE PRECISION NULL,
    VAL_MOD_CONST DOUBLE PRECISION NULL,
    INDIC_COEF_CORR CHARACTER VARYING(10) NULL,
    VALT_COEF_COR_S DOUBLE PRECISION NULL,
    VALT_COEF_COR_C DOUBLE PRECISION NULL,
    VALT_COEF_COR_SYC DOUBLE PRECISION NULL,
    DES_COD_DESTINO CHARACTER VARYING(15) NULL
);


CREATE TABLE ELCAT 
(
    ELCAT_CD CHARACTER VARYING(15) NOT NULL,
    ELCAT_DS CHARACTER VARYING(50) NULL,
    ELCAT_TP CHARACTER VARYING(1) NULL
);


CREATE TABLE HABIT 
(
    PERSN_NIP CHARACTER VARYING(15) NOT NULL,
    HABIT_NIA CHARACTER VARYING(15) NULL,
    HABIT_DTPD DATE NULL,
    HABIT_SEX CHARACTER VARYING(1) NULL,
    HABIT_DTNX DATE NULL,
    HABIT_MUNX CHARACTER VARYING(3) NULL,
    HABIT_PRNX CHARACTER VARYING(2) NULL,
    HABIT_PANX CHARACTER VARYING(3) NULL,
    HABIT_NCIO CHARACTER VARYING(3) NULL,
    HABIT_INST CHARACTER VARYING(3) NULL,
    HABIT_MOV CHARACTER VARYING(3) NULL,
    HABIT_DTMV DATE NULL,
    HABIT_NUC CHARACTER VARYING(30) NULL,
    HABIT_HAB CHARACTER VARYING(20) NULL
);


CREATE TABLE ILCEN 
(
    ILCEN_CD CHARACTER VARYING(8) NOT NULL,
    SECCE_CD CHARACTER VARYING(5) NOT NULL,
    BARRI_CD CHARACTER VARYING(3) NOT NULL
);


CREATE TABLE LOCAL 
(
    LOCAL_CD CHARACTER VARYING(10) NOT NULL,
    ECONS_CD CHARACTER VARYING(14) NOT NULL,
    UFISC_CD CHARACTER VARYING(11) NOT NULL,
    ADLOC_CD CHARACTER VARYING(14) NOT NULL
);


CREATE TABLE MUN 
(
    PROV_CD CHARACTER VARYING(2) NOT NULL,
    MUN_CD CHARACTER VARYING(3) NOT NULL,
    MUN_DGC CHARACTER VARYING(3) NULL,
    MUN_NM CHARACTER VARYING(50) NULL
);


CREATE TABLE PARCE 
(
    REFCAD_PAR CHARACTER VARYING(14) NOT NULL,
    REFPAR_1 CHARACTER VARYING(7) NULL,
    REFPAR_2 CHARACTER VARYING(7) NULL,
    ILCAD_CD CHARACTER VARYING(5) NOT NULL,
    ILCEN_CD CHARACTER VARYING(8) NULL,
    ID_VALORBI CHARACTER VARYING(2) NULL,
    F_SUPFINCA INTEGER NULL,
    F_SUPCONTOTAL INTEGER NULL,
    F_SUPCONSBRAS INTEGER NULL,
    F_SUPCONBJRAS INTEGER NULL,
    F_SUPCUBIERTA INTEGER NULL,
    F_COORX DOUBLE PRECISION NULL,
    F_COORY DOUBLE PRECISION NULL,
    E_CALCULO INTEGER NULL,
    E_MODREPARTO CHARACTER VARYING(1) NULL,
    E_INFRAEDIF CHARACTER VARYING(1) NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL,
    HUSO_GEO CHARACTER VARYING(10) NULL,
    REF_CAT_BICE CHARACTER VARYING(20) NULL,
    DENO_BICE CHARACTER VARYING(65) NULL
);


CREATE TABLE PERSN 
(
    PERSN_NIP CHARACTER VARYING(15) NOT NULL,
    ADLOC_CD CHARACTER VARYING(14) NOT NULL,
    PERSN_NIF CHARACTER VARYING(9) NULL,
    PERSN_ANIF CHARACTER VARYING(1) NULL,
    PERSN_DOC CHARACTER VARYING(15) NULL,
    PERSN_TDOC CHARACTER VARYING(1) NULL,
    PERSN_TP CHARACTER VARYING(1) NULL,
    PERSN_COG1 CHARACTER VARYING(40) NULL,
    PERSN_COG2 CHARACTER VARYING(40) NULL,
    PERSN_NOM CHARACTER VARYING(20) NULL,
    PERSN_COMP CHARACTER VARYING(20) NULL,
    PERSN_MAIL CHARACTER VARYING(30) NULL,
    PERSN_TELF CHARACTER VARYING(12) NULL
);


CREATE TABLE POVAL 
(
    POVAL_ID CHARACTER VARYING(3) NOT NULL,
    POVAL_NM CHARACTER VARYING(30) NULL,
    POVAL_ANY INTEGER NULL,
    POVAL_MBC INTEGER NULL,
    POVAL_IMBC DOUBLE PRECISION NULL,
    POVAL_MBR INTEGER NULL,
    POVAL_IMBR DOUBLE PRECISION NULL,
    POVAL_GB DOUBLE PRECISION NULL,
    POVAL_GBUN DOUBLE PRECISION NULL,
    POVAL_VUB CHARACTER VARYING(3) NULL,
    POVAL_IVUB DOUBLE PRECISION NULL,
    POVAL_VRB CHARACTER VARYING(3) NULL,
    POVAL_IVRB DOUBLE PRECISION NULL,
    POVAL_DISS CHARACTER VARYING(1) NULL
);


CREATE TABLE PROV 
(
    PROV_CD CHARACTER VARYING(2) NOT NULL,
    PROV_NM CHARACTER VARYING(30) NULL
);


CREATE TABLE QUSOL 
(
    QUSOL_CD CHARACTER VARYING(3) NOT NULL,
    CLSOL_CD CHARACTER VARYING(4) NOT NULL,
    QUSOL_CL CHARACTER VARYING(15) NULL,
    QUSOL_DS CHARACTER VARYING(100) NULL,
    QUSOL_TP CHARACTER VARYING(8) NULL,
    QUSOL_US CHARACTER VARYING(25) NULL,
    QUSOL_ORD CHARACTER VARYING(25) NULL,
    QUSOL_VAR CHARACTER VARYING(25) NULL,
    QUSOL_FAC DOUBLE PRECISION NULL,
    QUSOL_FON DOUBLE PRECISION NULL,
    QUSOL_SMIN DOUBLE PRECISION NULL,
    QUSOL_NPLA INTEGER NULL,
    QUSOL_EDIF DOUBLE PRECISION NULL,
    QUSOL_OBS CHARACTER VARYING(255) NULL,
    QUSOL_EXP CHARACTER VARYING(16) NULL,
    QUSOL_EDGU CHARACTER VARYING(11) NULL
);


CREATE TABLE RPFIS 
(
    ECOMU_CD CHARACTER VARYING(10) NOT NULL,
    UFISC_CD CHARACTER VARYING(11) NOT NULL,
    RPFIS_PC DOUBLE PRECISION NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT DATE NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL
);


CREATE TABLE RPLOC 
(
    ECOMU_CD CHARACTER VARYING(10) NOT NULL,
    LOCAL_CD CHARACTER VARYING(10) NOT NULL,
    RPLOC_PC DOUBLE PRECISION NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL
);


CREATE TABLE SECCE 
(
    SECCE_CD CHARACTER VARYING(5) NOT NULL,
    SECCE_NR CHARACTER VARYING(3) NULL,
    DISTR_CD CHARACTER VARYING(2) NOT NULL
);


CREATE TABLE SECTO 
(
    SECTO_CD CHARACTER VARYING(3) NOT NULL,
    SECTO_DS CHARACTER VARYING(60) NULL,
    CLSOL_CD CHARACTER VARYING(4) NOT NULL,
    SECTO_ES CHARACTER VARYING(12) NULL,
    SECTO_GS CHARACTER VARYING(25) NULL,
    SECTO_SP DOUBLE PRECISION NULL,
    SECTO_SM DOUBLE PRECISION NULL,
    SECTO_ED DOUBLE PRECISION NULL,
    SECTO_SR DOUBLE PRECISION NULL,
    SECTO_NR INTEGER NULL,
    SECTO_SI DOUBLE PRECISION NULL,
    SECTO_NI INTEGER NULL,
    SECTO_ST DOUBLE PRECISION NULL,
    SECTO_NT INTEGER NULL,
    SECTO_OBS CHARACTER VARYING(255) NULL
);


CREATE TABLE SUBPA 
(
    SUBPA_CD CHARACTER VARYING(9) NOT NULL,
    REFCAD_PAR CHARACTER VARYING(14) NOT NULL,
    SUBPA_TP CHARACTER VARYING(25) NULL,
    SUBPA_NPL INTEGER NULL,
    SUBPA_NPLS INTEGER NULL,
    SUBPA_PARCE CHARACTER VARYING(2) NULL,
    SUBPA_DATALTA DATE NULL,
    SUBPA_DATABAIX DATE NULL,
    SUBPA_SOTERR CHARACTER VARYING(1) NULL,
    SUBPA_EXPED CHARACTER VARYING(13) NULL
);


CREATE TABLE TICAD 
(
    PERSN_NIP CHARACTER VARYING(15) NOT NULL,
    TICAD_CON CHARACTER VARYING(9) NULL,
    TICAD_CB CHARACTER VARYING(9) NULL,
    TICAD_COMP CHARACTER VARYING(20) NULL,
    TICAD_BANC CHARACTER VARYING(4) NULL,
    TICAD_AGEN CHARACTER VARYING(4) NULL,
    TICAD_CPTE CHARACTER VARYING(12) NULL
);


CREATE TABLE TIFIS 
(
    UFISC_CD CHARACTER VARYING(11) NOT NULL,
    PERSN_NIP CHARACTER VARYING(15) NOT NULL,
    DER_CODIGO CHARACTER VARYING(2) NULL,
    DER_PORCENT DOUBLE PRECISION NULL,
    DER_ORDINAL INTEGER NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL
);


CREATE TABLE TRCAR 
(
    PROV_CD CHARACTER VARYING(2) NOT NULL,
    MUN_CD CHARACTER VARYING(3) NOT NULL,
    CARRE_CD CHARACTER VARYING(4) NOT NULL,
    TRCAR_CD CHARACTER VARYING(6) NOT NULL,
    TRCAR_DGC CHARACTER VARYING(6) NULL,
    NUMINI_EQ INTEGER NULL,
    LETINI_EQ CHARACTER VARYING(1) NULL,
    NUMFIN_EQ INTEGER NULL,
    LETFIN_EQ CHARACTER VARYING(1) NULL,
    NUMINI_DR INTEGER NULL,
    LETINI_DR CHARACTER VARYING(1) NULL,
    NUMFIN_DR INTEGER NULL,
    LETFIN_DR CHARACTER VARYING(1) NULL,
    CALCA_TIPCAR CHARACTER VARYING(2) NULL,
    CALCA_SENTIT CHARACTER VARYING(2) NULL,
    CALCA_AMPLE DOUBLE PRECISION NULL,
    CALCA_PMOBILITAT CHARACTER VARYING(2) NULL,
    CALCA_CBICI CHARACTER VARYING(2) NULL,
    CALCA_CARRET CHARACTER VARYING(8) NULL,
    CALCA_TITU CHARACTER VARYING(20) NULL,
    URBA CHARACTER VARYING(1) NULL,
    ILCEN_CD_E CHARACTER VARYING(8) NULL,
    ILCEN_CD_D CHARACTER VARYING(8) NULL
);


CREATE TABLE UCONS 
(
    UCONS_CD CHARACTER VARYING(10) NOT NULL,
    REFCAD_PAR CHARACTER VARYING(14) NOT NULL,
    ZNVAL_ID CHARACTER VARYING(5) NOT NULL,
    ID_CLASE CHARACTER VARYING(2) NULL,
    F_ANYOCONSTR INTEGER NULL,
    F_IND CHARACTER VARYING(1) NULL,
    F_SUP INTEGER NULL,
    F_LONG INTEGER NULL,
    E_CODVIA CHARACTER VARYING(4) NULL,
    E_CODTRAMO CHARACTER VARYING(6) NULL,
    E_CCVSC_NUM_1 CHARACTER VARYING(1) NULL,
    E_CCVSC_IND_1 CHARACTER VARYING(1) NULL,
    E_CCVC_COEF_1 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_IND_1 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_COEF_1 DOUBLE PRECISION NULL,
    E_CCCVSYC_IND_2 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_IND_3 CHARACTER VARYING(1) NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL,
    F2_CODUC_MATRIZ CHARACTER VARYING(10) NULL,
    DES_COD_DESTINO CHARACTER VARYING(15) NULL,
    IMP_VAL_UNI_SUELO INTEGER NULL
);


CREATE TABLE UFISC 
(
    UFISC_CD CHARACTER VARYING(11) NOT NULL,
    REFCAD_PAR CHARACTER VARYING(14) NOT NULL,
    UFISC_NR INTEGER NULL,
    UFISC_CL CHARACTER VARYING(2) NULL,
    ID_CTRL_1 CHARACTER VARYING(1) NULL,
    ID_CTRL_2 CHARACTER VARYING(1) NULL,
    ID_NUMFIJO INTEGER NULL,
    ID_NUMREGISTRAL CHARACTER VARYING(19) NULL,
    INFO_PRECIO DOUBLE PRECISION NULL,
    INFO_ORIGPRECIO CHARACTER VARYING(1) NULL,
    INFO_PRECIOVTA DOUBLE PRECISION NULL,
    INFO_ANYOFIN INTEGER NULL,
    INFO_TIPOPROP CHARACTER VARYING(1) NULL,
    INFO_NUMORDEN CHARACTER VARYING(4) NULL,
    INFO_ANYOANTI INTEGER NULL,
    E_EJERCICIO INTEGER NULL,
    E_VALOR DOUBLE PRECISION NULL,
    E_VALORSUELO DOUBLE PRECISION NULL,
    E_VALORCONSTR DOUBLE PRECISION NULL,
    E_BASELIQUIDABLE DOUBLE PRECISION NULL,
    E_CLAVEUSO CHARACTER VARYING(1) NULL,
    E_IMPORTE DOUBLE PRECISION NULL,
    E_CLAVEBONIF CHARACTER VARYING(1) NULL,
    E_SUPFINCA INTEGER NULL,
    E_SUPSOLAR INTEGER NULL,
    E_COEFPROP DOUBLE PRECISION NULL,
    E_VALORBASE DOUBLE PRECISION NULL,
    E_PROCVALORBASE CHARACTER VARYING(1) NULL,
    E_EJERIBI INTEGER NULL,
    E_VALORIBI DOUBLE PRECISION NULL,
    E_REVISION INTEGER NULL,
    E_REVISIONPAR INTEGER NULL,
    E_PERIODO INTEGER NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL,
    DES_COD_USO CHARACTER VARYING(15) NULL,
    VAL_CAT_SUELO_A DOUBLE PRECISION NULL,
    VAL_CAT_SUELO_R DOUBLE PRECISION NULL,
    IMP_REDUCCION DOUBLE PRECISION NULL,
    ANYO_REDUCCION INTEGER NULL,
    EJER_VAL_SUELO_A INTEGER NULL,
    IND_VAL_CAT_MODIF CHARACTER VARYING(1) NULL,
    INFO_INEXIST_DOC CHARACTER VARYING(1) NULL
);


CREATE TABLE UNSOL 
(
    UNSOL_CD CHARACTER VARYING(9) NOT NULL,
    REFCAD_PAR CHARACTER VARYING(14) NOT NULL,
    ZNVAL_ID CHARACTER VARYING(5) NOT NULL,
    ZNURB_CD CHARACTER VARYING(10) NOT NULL,
    UNSOL_LGFC INTEGER NULL,
    UNSOL_TPFC CHARACTER VARYING(2) NULL,
    UNSOL_SP INTEGER NULL,
    UNSOL_LGFN INTEGER NULL,
    UNSOL_CODVIA CHARACTER VARYING(4) NULL,
    UNSOL_SCVAL CHARACTER VARYING(6) NULL,
    UNSOL_TPVL CHARACTER VARYING(1) NULL,
    E_CCVS_NUM_1 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_1 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_2 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_3 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_4 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_5 CHARACTER VARYING(1) NULL,
    E_CCVS_IND_6 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_COEF_1 DOUBLE PRECISION NULL,
    E_CCCVSYC_IND_1 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_COEF_2 DOUBLE PRECISION NULL,
    E_CCCVSYC_IND_2 CHARACTER VARYING(1) NULL,
    E_CCCVSYC_IND_3 CHARACTER VARYING(1) NULL,
    EXP_ANYO INTEGER NULL,
    EXP_REFERENCIA CHARACTER VARYING(13) NULL,
    EXP_CODENT INTEGER NULL,
    EXP_TIPOMOV CHARACTER VARYING(1) NULL,
    SAL_TIPOEXP CHARACTER VARYING(4) NULL,
    SAL_FECHAALT INTEGER NULL,
    SAL_EJERCICIO INTEGER NULL,
    SAL_EJENTIDAD INTEGER NULL,
    SAL_REFEXPENT CHARACTER VARYING(8) NULL,
    SAL_CODENT INTEGER NULL,
    SAL_REFEXP CHARACTER VARYING(8) NULL,
    SAL_CODENT_ALT INTEGER NULL,
    VAL_UNI_SUELO INTEGER NULL,
    INDIC_CC_APLIC CHARACTER VARYING(10) NULL,
    VAL_TOTAL_CC_S DOUBLE PRECISION NULL,
    VAL_TOTAL_CC_SYC DOUBLE PRECISION NULL
);


CREATE TABLE ZNURB 
(
    ZNURB_CD CHARACTER VARYING(10) NULL,
    EDIF_VIV DOUBLE PRECISION NULL,
    EDIF_COM DOUBLE PRECISION NULL,
    EDIF_OFI DOUBLE PRECISION NULL,
    EDIF_IND DOUBLE PRECISION NULL,
    EDIF_TUR DOUBLE PRECISION NULL,
    EDIF_ALT DOUBLE PRECISION NULL,
    EDIF_AL2 DOUBLE PRECISION NULL,
    EDIF_AL3 DOUBLE PRECISION NULL,
    EDIF_ZVD DOUBLE PRECISION NULL,
    EDIF_EQU DOUBLE PRECISION NULL,
    ZNURB_NM CHARACTER VARYING(30) NULL,
    ZNURB_FAC DOUBLE PRECISION NULL,
    ZNURB_FON DOUBLE PRECISION NULL,
    ZNURB_SMIN DOUBLE PRECISION NULL,
    ZNURB_NPLA INTEGER NULL,
    ZNURB_NPLS INTEGER NULL,
    ZNURB_QUACD CHARACTER VARYING(2) NULL,
    ZNURB_QUANM CHARACTER VARYING(30) NULL,
    ZNURB_ZONCD CHARACTER VARYING(2) NULL,
    ZNURB_ZONNM CHARACTER VARYING(30) NULL,
    ZNURB_OCUCD CHARACTER VARYING(2) NULL,
    ZNURB_OCUNM CHARACTER VARYING(30) NULL,
    ZNURB_ORDCD CHARACTER VARYING(1) NULL,
    ZNURB_ORDNM CHARACTER VARYING(30) NULL
);


CREATE TABLE ZNVAL 
(
    ZNVAL_ID CHARACTER VARYING(5) NULL,
    POVAL_ID CHARACTER VARYING(3) NOT NULL,
    ZNVAL_CD CHARACTER VARYING(4) NOT NULL,
    ZNVAL_TP CHARACTER VARYING(2) NULL,
    ZNVAL_NV CHARACTER VARYING(2) NULL,
    ZNVAL_VU DOUBLE PRECISION NULL,
    ZNVAL_VIV DOUBLE PRECISION NULL,
    ZNVAL_COM DOUBLE PRECISION NULL,
    ZNVAL_OFI DOUBLE PRECISION NULL,
    ZNVAL_IND DOUBLE PRECISION NULL,
    ZNVAL_TUR DOUBLE PRECISION NULL,
    ZNVAL_GAR DOUBLE PRECISION NULL,
    ZNVAL_ALT DOUBLE PRECISION NULL,
    ZNVAL_AL2 DOUBLE PRECISION NULL,
    ZNVAL_ZVD DOUBLE PRECISION NULL,
    ZNVAL_EQU DOUBLE PRECISION NULL,
    ZNVAL_VUIN DOUBLE PRECISION NULL
);


ALTER TABLE ADLOC 
  ADD CONSTRAINT PK_ADLOC PRIMARY KEY (
    ADLOC_CD)  ;
ALTER TABLE ADPOR 
  ADD CONSTRAINT PK_ADPOR PRIMARY KEY (
    ADPOR_CD)  ;
ALTER TABLE BARRI 
  ADD CONSTRAINT PK_BARRI PRIMARY KEY (
    BARRI_CD)  ;
ALTER TABLE CARRE 
  ADD CONSTRAINT PK_CARRE PRIMARY KEY (
    PROV_CD, MUN_CD, CARRE_CD)  ;
ALTER TABLE CLSOL 
  ADD CONSTRAINT PK_CLSOL PRIMARY KEY (
    CLSOL_CD)  ;
ALTER TABLE DISTR 
  ADD CONSTRAINT PK_DISTR PRIMARY KEY (
    DISTR_CD)  ;
ALTER TABLE ECOMU 
  ADD CONSTRAINT PK_ECOMU PRIMARY KEY (
    ECOMU_CD)  ;
ALTER TABLE ECONS 
  ADD CONSTRAINT PK_ECONS PRIMARY KEY (
    ECONS_CD)  ;
ALTER TABLE ELCAT 
  ADD CONSTRAINT PK_ELCAT PRIMARY KEY (
    ELCAT_CD)  ;
ALTER TABLE HABIT 
  ADD CONSTRAINT PK_HABIT PRIMARY KEY (
    PERSN_NIP)  ;
ALTER TABLE ILCEN 
  ADD CONSTRAINT PK_ILCEN PRIMARY KEY (
    ILCEN_CD)  ;
ALTER TABLE LOCAL 
  ADD CONSTRAINT PK_LOCAL PRIMARY KEY (
    LOCAL_CD)  ;
ALTER TABLE MUN 
  ADD CONSTRAINT PK_MUN PRIMARY KEY (
    PROV_CD, MUN_CD)  ;
ALTER TABLE PARCE 
  ADD CONSTRAINT PK_PARCE PRIMARY KEY (
    REFCAD_PAR)  ;
ALTER TABLE PERSN 
  ADD CONSTRAINT PK_PERSN PRIMARY KEY (
    PERSN_NIP)  ;
ALTER TABLE POVAL 
  ADD CONSTRAINT PK_POVAL PRIMARY KEY (
    POVAL_ID)  ;
ALTER TABLE PROV 
  ADD CONSTRAINT PK_PROV PRIMARY KEY (
    PROV_CD)  ;
ALTER TABLE QUSOL 
  ADD CONSTRAINT PK_QUSOL PRIMARY KEY (
    QUSOL_CD)  ;
ALTER TABLE RPFIS 
  ADD CONSTRAINT PK_RPFIS PRIMARY KEY (
    ECOMU_CD, UFISC_CD)  ;
ALTER TABLE RPLOC 
  ADD CONSTRAINT PK_RPLOC PRIMARY KEY (
    LOCAL_CD, ECOMU_CD)  ;
ALTER TABLE SECCE 
  ADD CONSTRAINT PK_SECCE PRIMARY KEY (
    SECCE_CD)  ;
ALTER TABLE SECTO 
  ADD CONSTRAINT PK_SECTO PRIMARY KEY (
    SECTO_CD)  ;
ALTER TABLE SUBPA 
  ADD CONSTRAINT PK_SUBPA PRIMARY KEY (
    SUBPA_CD)  ;
ALTER TABLE TICAD 
  ADD CONSTRAINT PK_TICAD PRIMARY KEY (
    PERSN_NIP)  ;
ALTER TABLE TIFIS 
  ADD CONSTRAINT PK_TIFIS PRIMARY KEY (
    PERSN_NIP, UFISC_CD)  ;
ALTER TABLE TRCAR 
  ADD CONSTRAINT PK_TRCAR PRIMARY KEY (
    PROV_CD, MUN_CD, CARRE_CD, TRCAR_CD)  ;
ALTER TABLE UCONS 
  ADD CONSTRAINT PK_UCONS PRIMARY KEY (
    UCONS_CD)  ;
ALTER TABLE UFISC 
  ADD CONSTRAINT PK_UFISC PRIMARY KEY (
    UFISC_CD)  ;
ALTER TABLE UNSOL 
  ADD CONSTRAINT PK_UNSOL PRIMARY KEY (
    UNSOL_CD)  ;
ALTER TABLE ZNURB 
  ADD CONSTRAINT PK_ZNURB PRIMARY KEY (
    ZNURB_CD)  ;
ALTER TABLE ZNVAL 
  ADD CONSTRAINT PK_ZNVAL PRIMARY KEY (
    ZNVAL_ID)  ;
	
	
	
	
ALTER TABLE LOCAL
  ADD CONSTRAINT FK_ADLOC 
    FOREIGN KEY (ADLOC_CD)
      REFERENCES ADLOC;

ALTER TABLE PERSN
  ADD CONSTRAINT FK_ADPER 
    FOREIGN KEY (ADLOC_CD)
      REFERENCES ADLOC;

ALTER TABLE ILCEN
  ADD CONSTRAINT FK_BARCEN 
    FOREIGN KEY (BARRI_CD)
      REFERENCES BARRI;

ALTER TABLE TRCAR
  ADD CONSTRAINT FK_CARTRA 
    FOREIGN KEY (PROV_CD, MUN_CD, CARRE_CD)
      REFERENCES CARRE;

ALTER TABLE QUSOL
  ADD CONSTRAINT FK_CLQU 
    FOREIGN KEY (CLSOL_CD)
      REFERENCES CLSOL;

ALTER TABLE SECTO
  ADD CONSTRAINT FK_CLSEC 
    FOREIGN KEY (CLSOL_CD)
      REFERENCES CLSOL;

ALTER TABLE SECCE
  ADD CONSTRAINT FK_DISEC 
    FOREIGN KEY (DISTR_CD)
      REFERENCES DISTR;

ALTER TABLE ECOMU
  ADD CONSTRAINT FK_ECOCOM 
    FOREIGN KEY (ECONS_CD)
      REFERENCES ECONS;

ALTER TABLE LOCAL
  ADD CONSTRAINT FK_ECOLOC 
    FOREIGN KEY (ECONS_CD)
      REFERENCES ECONS;

ALTER TABLE RPFIS
  ADD CONSTRAINT FK_ECORPF 
    FOREIGN KEY (ECOMU_CD)
      REFERENCES ECOMU;

ALTER TABLE RPLOC
  ADD CONSTRAINT FK_ECORPL 
    FOREIGN KEY (ECOMU_CD)
      REFERENCES ECOMU;

ALTER TABLE RPFIS
  ADD CONSTRAINT FK_FISRPF 
    FOREIGN KEY (UFISC_CD)
      REFERENCES UFISC;

ALTER TABLE TRCAR
  ADD CONSTRAINT FK_ILCETRAD 
    FOREIGN KEY (ILCEN_CD_D)
      REFERENCES ILCEN;

ALTER TABLE TRCAR
  ADD CONSTRAINT FK_ILCETRAE 
    FOREIGN KEY (ILCEN_CD_E)
      REFERENCES ILCEN;

ALTER TABLE RPLOC
  ADD CONSTRAINT FK_LOCRPL 
    FOREIGN KEY (LOCAL_CD)
      REFERENCES LOCAL;

ALTER TABLE CARRE
  ADD CONSTRAINT FK_MUNCAR 
    FOREIGN KEY (PROV_CD, MUN_CD)
      REFERENCES MUN;

ALTER TABLE UNSOL
  ADD CONSTRAINT FK_PARSOL 
    FOREIGN KEY (REFCAD_PAR)
      REFERENCES PARCE;

ALTER TABLE SUBPA
  ADD CONSTRAINT FK_PARSUB 
    FOREIGN KEY (REFCAD_PAR)
      REFERENCES PARCE;

ALTER TABLE UCONS
  ADD CONSTRAINT FK_PARUCO 
    FOREIGN KEY (REFCAD_PAR)
      REFERENCES PARCE;

ALTER TABLE UFISC
  ADD CONSTRAINT FK_PARUFI 
    FOREIGN KEY (REFCAD_PAR)
      REFERENCES PARCE;

ALTER TABLE HABIT
  ADD CONSTRAINT FK_PERHAB 
    FOREIGN KEY (PERSN_NIP)
      REFERENCES PERSN;

ALTER TABLE TICAD
  ADD CONSTRAINT FK_PERTIC 
    FOREIGN KEY (PERSN_NIP)
      REFERENCES PERSN;

ALTER TABLE ADLOC
  ADD CONSTRAINT FK_PORADL 
    FOREIGN KEY (ADPOR_CD)
      REFERENCES ADPOR;

ALTER TABLE ZNVAL
  ADD CONSTRAINT FK_POVZN 
    FOREIGN KEY (POVAL_ID)
      REFERENCES POVAL;

ALTER TABLE MUN
  ADD CONSTRAINT FK_PROVMUN 
    FOREIGN KEY (PROV_CD)
      REFERENCES PROV;

ALTER TABLE ILCEN
  ADD CONSTRAINT FK_SECCEN 
    FOREIGN KEY (SECCE_CD)
      REFERENCES SECCE;

ALTER TABLE TIFIS
  ADD CONSTRAINT FK_TICTIF 
    FOREIGN KEY (PERSN_NIP)
      REFERENCES TICAD;

ALTER TABLE ADPOR
  ADD CONSTRAINT FK_TRAPOR 
    FOREIGN KEY (PROV_CD, MUN_CD, CARRE_CD, TRCAR_CD)
      REFERENCES TRCAR;

ALTER TABLE ECONS
  ADD CONSTRAINT FK_UCONS 
    FOREIGN KEY (UCONS_CD)
      REFERENCES UCONS;

ALTER TABLE LOCAL
  ADD CONSTRAINT FK_UFILOC 
    FOREIGN KEY (UFISC_CD)
      REFERENCES UFISC;

ALTER TABLE TIFIS
  ADD CONSTRAINT FK_UFITIF 
    FOREIGN KEY (UFISC_CD)
      REFERENCES UFISC;

ALTER TABLE UNSOL
  ADD CONSTRAINT FK_URBSOL 
    FOREIGN KEY (ZNURB_CD)
      REFERENCES ZNURB;

ALTER TABLE UNSOL
  ADD CONSTRAINT FK_VALSOL 
    FOREIGN KEY (ZNVAL_ID)
      REFERENCES ZNVAL;

ALTER TABLE UCONS
  ADD CONSTRAINT FK_VALUCO 
    FOREIGN KEY (ZNVAL_ID)
      REFERENCES ZNVAL;



